version: '3.4'
services:
  trustlines-bridge.dnp.dappnode.eth:
    image: 'trustlines-bridge.dnp.dappnode.eth:0.1.0'
    build: ./build
    volumes:
      - 'trustlines-validatordnpdappnodeeth_config:/config:ro'
volumes:
  trustlines-validatordnpdappnodeeth_config:
    external: true
